### ISSUE TITLE
Varnish 4 compatability?

### ISSUE THREAD

**Issue by jhmartin** [comotion/VSF#15]
Is VSF compatible with Varnish 4?

**Comment by fgsch** [comment]
The master branch should work with V4 but it's work in progress.
There might be some bugs and documentation on that is missing though.

**Comment by fgsch** [comment]
On a related subject, we should mention vcl_dir and use it for testing.

**Comment by comotion** [comment]
Yes, VSF is 4.x compatible now. Varnish 4.1 recommended.
