### ISSUE TITLE
Centos 6 + VSF + Varnish 4.1

### ISSUE THREAD

**Issue by hellracer** [comotion/VSF#22]
Hi guys,

any hint on how can I past this error?

bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -I/usr/include/varnish -I../../utf8proc -std=c99 -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c -o libvmod_vsf_la-vmod_vsf.lo `test -f 'vmod_vsf.c' || echo './'`vmod_vsf.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -I../../utf8proc -std=c99 -g -O2 -MT libvmod_vsf_la-vmod_vsf.lo -MD -MP -MF .deps/libvmod_vsf_la-vmod_vsf.Tpo -c vmod_vsf.c  -fPIC -DPIC -o .libs/libvmod_vsf_la-vmod_vsf.o
vmod_vsf.c: In function ‘vmod_body’:
vmod_vsf.c:134: warning: implicit declaration of function ‘strncasecmp’
vmod_vsf.c: In function ‘vmod_normalize’:
vmod_vsf.c:206: error: ‘utf8proc_ssize_t’ undeclared (first use in this function)
vmod_vsf.c:206: error: (Each undeclared identifier is reported only once
vmod_vsf.c:206: error: for each function it appears in.)
vmod_vsf.c:206: error: expected ‘;’ before ‘len’
vmod_vsf.c:224: error: ‘len’ undeclared (first use in this function)
vmod_vsf.c:224: error: ‘utf8proc_uint8_t’ undeclared (first use in this function)
vmod_vsf.c:224: error: expected expression before ‘)’ token
vmod_vsf.c:225: error: too few arguments to function ‘utf8proc_decompose’
vmod_vsf.c:234: error: ‘utf8proc_int32_t’ undeclared (first use in this function)
vmod_vsf.c:234: error: expected expression before ‘)’ token
vmod_vsf.c:234: error: too few arguments to function ‘utf8proc_reencode’
make[2]: *** [libvmod_vsf_la-vmod_vsf.lo] Error 1
make[2]: Leaving directory `/root/vmod/VSF/libvmod-vsf/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/vmod/VSF/libvmod-vsf'
make: *** [all] Error 2

**Comment by hellracer** [comment]
Additional Information utf8proc was get from rpmforge repo.

[root@varnish varnish]# rpm -qa | grep utf8proc
utf8proc-1.1.4-1.el6.rf.x86_64
utf8proc-devel-1.1.4-1.el6.rf.x86_64
[root@varnish varnish]#

**Comment by comotion** [comment]
hia. which commit of VSF are you at? the newest VSF vmod does not use your systemwide utf8proc, so you can remove that. just follow the README install instructions.

**Comment by comotion** [comment]
I took a stab at compiling things on centos6, and in the process simplified the process. See the README - there is now a toplevel `make` you can call. 
Please let us know how it goes!

**Comment by hellracer** [comment]
Will surely do. I'm going to remove everything and retry from scratch, I'll revert back on this asap, thanks for looking into this.

**Comment by comotion** [comment]
How did it go?

**Comment by fgsch** [comment]
@hellracer can you confirm whether this is fixed now?

**Comment by fgsch** [comment]
Timed out. 

If you are still experiencing this error please reopen this ticket.
