### ISSUE TITLE
cmd changes

### ISSUE THREAD

**Issue by blindpet** [comotion/VSF#29]
I have been doing pentesting today with command lines and can confirm you need a whitespace or %20. I would recommend adding an rm check too. Here is my attempt at a pull request for 3.0 and 4.0

https://github.com/blindpet/VSF/commit/50ccfc1aec64e1c8bf337a4cedf65309deb31a0c
https://github.com/blindpet/VSF/commit/fd86e2138cd6176bb52bfbe5242ebb88da25f558

**Comment by comotion** [comment]
I've reviewed the diffs and approve. If you make a real pull request with just these changes and I will commit it.

**Comment by blindpet** [comment]
I will make an attempt, last time didn't go so well. I have tried again but may have done it wrong. My apologies if it's not quite right.
