### ISSUE TITLE
Error Installing on Centos 7 and Varnish 4.0.3 compliled from source

### ISSUE THREAD

**Issue by brunorossi** [comotion/VSF#33]
cd opt/
git clone https://github.com/comotion/VSF.git
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
cd VSF/
make

...
/configure: line 11523: VARNISH_VMOD_INCLUDES: command not found
./configure: line 11524: VARNISH_VMOD_DIR: command not found
./configure: line 11525: VARNISH_VMODTOOL: command not found
checking for varnishtest... /usr/local/bin/varnishtest
checking for varnishd... /usr/local/sbin/varnishd
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make[1]: Entering directory `/opt/VSF/libvmod-vsf'
make  all-recursive
make[2]: Entering directory `/opt/VSF/libvmod-vsf'
Making all in src
make[3]: Entering directory `/opt/VSF/libvmod-vsf/src'
/usr/bin/python2.7  ../src/vmod.vcc
File "../src/vmod.vcc", line 27
$Module vsf 3 Varnish Security Firewall
...

**Comment by comotion** [comment]
Hi - this looks like a case of missing dependencies.
Do you have automake, autoconf and friends?
Please provide the full log.

**Comment by brunorossi** [comment]
Ok, i will send you all the logs and installing bash script asap. Thank you

**Comment by fgsch** [comment]
Please note that VSF did not support Varnish versions lower than 4.1 before today.
The 4.0 branch supports 4.0 but lacks the ability to inspect the body since this functionality is not available in Varnish 4.0.

**Comment by fgsch** [comment]
I've added some checks and support for PKG_CONFIG_PATH. Please update your tree and try again. 

If it's still happening feel free to reopen this ticket.
