### ISSUE TITLE
Limit requests not per IP, but to vhost

### ISSUE THREAD

**Issue by intelbg** [comotion/VSF#40]
Hello,
I would like to ask you if there is away through VSF/throttle or shield limit xmlrpc queries, but not only from one IP but to vhost, for example if there is limit 15 - and these 15 queries are from different IP-s to be blocked. Now they are blocked only if these 15 requests are reached from one IP. This is the current configuration:

f ((req.url ~ "(wp-login.php|xmlrpc.php)")) {
if(throttle.is_allowed("ip:" + client.ip, "10req/s") > 0s) {
error 429 "Calm down";
shield.conn_reset();
}
}

For example, can I use some variable instead of client.ip that points not 15 queries from the source IP, but 15 total requests from any IP to the vhost (without actually to write a different block for every vhost).
Thank you in advamce.

**Comment by comotion** [comment]
you could write your own throttle statement which checks the host header instead of client.ip. For instance:
```
if(throttle.is_allowed("host:" + req.http.host, "15req/s") > 0s) {
   error 429 "Calm down";
   shield.conn_reset();
}```

**Comment by intelbg** [comment]
I understant. What I see is that in varnishlog there is 503 service unavailable when flood to xmlrpc.php is occured, but it seems that this vmod just don't stop the flooad and do nothing, but the server loads more and more. My question is how I can understand if varnish don't do nothing and can I block request for a couple of time, not just to reset the connection? Also, is there a chance the postition of the code block to be wring - here is the limits.conf which is included in default.vcl:

 sub vcl_recv {

# throttle limits for xmlrpx and wp-login

if ((req.url ~ "(wp-login.php|xmlrpc.php)")) {
if(throttle.is_allowed("ip:" + client.ip, "10req/s") > 0s) {
error 429 "Calm down";
shield.conn_reset();
}
}

# Global throttle

if(throttle.is_allowed("ip:" + client.ip, "200req/s") > 0s) {
error 429 "Calm down";
}

# Throttle limit for vhost

if (req.http.host == "bu.bu.bu" || req.http.host == "www.bu.bu.bu") {
if(throttle.is_allowed("ip:" + client.ip, "30req/s") > 0s) {
error 429 "Too many requests";
}
}
}

**Comment by intelbg** [comment]
What I saw this time is that the implementation works but from 1000 
concurrent requests with the following configuration only 5 requests are 
failed from 1000 (and I awlays catch these requests that does not fails):

if ((req.url ~ "(wp-login.php|xmlrpc.php)")) {
    if(throttle.is_allowed("host:" + req.http.host, "10req/s") > 0s) {
    error 429 "Calm down";
    shield.conn_reset();
}
}

Is this a normal behavior and why so little number of requests is blocked?

**Comment by intelbg** [comment]
Is there an info that describe how these requests are handled and 
solution of this problem? If I set the throttle to 1 requests it works 
but this is super stupid and I can't understand why on 10 requests/s 
limit the throttle do nothing. If I can't solve this issue I should 
change the varnish with something other so I will be really thankfull if 
you help with this.

**Comment by comotion** [comment]
Hi,
the documentation for the 3.x throttle module you are using is here: https://github.com/nand2/libvmod-throttle

From what you write, I can't really tell you what's wrong. It is especially not clear to me that you are saying throttling at 1req/s works while 10req/s does not.

However, the world has moved on to Varnish 4.1 and vsthrottle, which is a re-implementation of throttling. I would suggest upgrading to VSF 4 and Varnish 4.1. This would aid greatly anyone trying to reproduce your problems.

**Comment by intelbg** [comment]
One, 2 months ago these vmods were not supported and creators told me to 
use 3.X. The problem is as I said that with limit 10req/s and flood with 
1000 concurent connections, only 5 requests are failed from 1000 - so 
this implementation just don't stop the flood and doesn't work as well. 
I can't change the version at this time.
