### ISSUE TITLE
Noob Installation Instructions?

### ISSUE THREAD

**Issue by rafaelmagic** [comotion/VSF#5]
Hi,

Can you update your instructions with Step by Step for noobs like me.

I found this installation tutorial for CentOS 6. 

http://www.screwloose.com.au/install-varnish-3-0-with-vsf-varnish-security-firewall-on-centos-6

But I am not sure if the steps are complete since some of the VMods have their own "Make" file. Please advice.

**Comment by comotion** [comment]
making packaging & installation easier is pretty high on the todo list. Reason we've waited this long is the long wait for varnish 4.1. any contributed packaging is appreciated

**Comment by comotion** [comment]
I have updated the readme to include installation instructions, and all of the required vmods requried have been folded into vmod-vsf. vsthrottle is optional but the readme includes install instructions for that as well. Distro specific packages is a different ticket, #21.
