### ISSUE TITLE
Is this project alive?!

### ISSUE THREAD

**Issue by realquaker** [comotion/VSF#51]
Hi,
Is this project alive?!
I'm interesting in it.

Thanks in advance for the answer.

**Comment by comotion** [comment]
Personally, I am no longer in a place where I have use for an application firewall. I've seen @fgsch close some tickets recently though, so I can only speak for myself.

**Comment by fgsch** [comment]
Sorry. I've been extremely busy but I do plan to attend to this soonish.

**Comment by realquaker** [comment]
Hi,
Great news.
Thanks for the answer!
