### ISSUE TITLE
VSF log

### ISSUE THREAD

**Issue by iammeken** [comotion/VSF#72]
Where to find log file of VSF?

I may need fail2ban to scan it.  :)

Thank you!

**Comment by fgsch** [comment]
Hi. Logs are currently emitted using [std.log](https://varnish-cache.org/docs/trunk/reference/vmod_std.html#std-log).
They should appear in the shared memory log and you can use tools such as varnishlog to get them.

Logging takes place in a few places, but the main entry is here (for the 6.0 branch): https://github.com/comotion/VSF/blob/6.0/vcl/handlers.vcl#L29.

Let me know if that answers your question.

**Comment by iammeken** [comment]
Thank you for answering me!

So there is no a thing like varnishncsa.log, for fail2ban to scan and block repeated bad ip addresses?

**Comment by fgsch** [comment]
You could set up varnishncsa to extract anything from the shared log so it should be possible, but you will need to implement it.

**Comment by iammeken** [comment]
Thank you for the hint, I will study it.
