### ISSUE TITLE
VSF 6.6 branch?

### ISSUE THREAD

**Issue by iammeken** [comotion/VSF#79]
Please put back 6.6 branch.

Ubuntu 22.04 comes with varnish 6.6 by default.

Thanks!

**Comment by fgsch** [comment]
Hi. Sorry, I've missed this. 

I've not put back the 6.6 branch but you have closed it, so I assume no action is needed.
Let me know if that's not the case. 

Thanks!

**Comment by iammeken** [comment]
You can put it back. I was appealing for others. I myself have backup. :)
